basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: A simple listing service API
  title: Listing API
  version: "1.0"
paths:
  /health:
    get:
      description: Get the health status of the API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check endpoint
      tags:
      - health
swagger: "2.0"
